print("**************************************")
print("**          Mahad Muzaffar          **")
print("**         Computer Science         **")
print("**                15                **")
print("**************************************")